apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider-tesopro-front
  namespace: tesopro
spec:
  provider: aws
  secretObjects:
    - secretName: secrets-qa-bff-tesopro-front
      type: Opaque
      data:
        - objectName: channels-collaborator-apiclient
          key: collaborator-apiclient
        - objectName: channels-collaborator-apisecret
          key: collaborator-apisecret
  parameters:
    objects: |
      - objectName: "APIKey/qa/channels/collaborators/tesoreria"
        objectType: secretsmanager
        jmesPath:
          - path: clientid
            objectAlias: channels-collaborator-apiclient
          - path: clientsecret
            objectAlias: channels-collaborator-apisecret
