replicaCount: 1

serviceAccount: tesopro-qa-sa

volumes:
  list:
  - name: secrets-store-inline
    csi: 
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: secrets-provider-tesopro-front


nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

container:
  image:
    pullPolicy: Always
  ports:
    - name: http
      containerPort: 8082
      protocol: TCP
  volumeMounts:
    list:
     - name: secrets-store-inline
       mountPath: "/mnt/secrets-store"
       readOnly: true

vars:
  enabled: true
  list:
      - name: REACT_APP_BASE_URL
        value: https://gw.qa.apis.itau.cl/channels/collaborators/tesoreria/v1
      - name: REACT_APP_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: secrets-qa-bff-tesopro-front
            key: collaborator-apiclient
      - name: REACT_APP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: secrets-qa-bff-tesopro-front
            key: collaborator-apisecret
      - name: REACT_APP_AUTHORITY_URL
        value: https://login.microsoftonline.com/9f4ba6d4-caa0-4b65-bbc9-687b3123882b
      - name: REACT_APP_AD_CLIENT_ID
        value: d8417ede-4cad-4c7f-8927-9030b5419a2f
      - name: REACT_APP_ENV_STATUS
        value: OK
      - name: PORT
        value: "8082"

secrets:

livenessEnabled: true
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessEnabled: true
readinessProbe:
  httpGet:
    path: /health
    port: /http
  initialDelaySeconds: 5
  periodSeconds: 10

service:
  type: ClusterIP
  port: 8082

ingress:
  ingressClassName: ingress-internal
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/group.name: alb-qa-front-priv
    alb.ingress.kubernetes.io/healthchek-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:970733212581:certificate/da8bfefe-b9d9-4658-9d53-d7b7d009a0a6
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  rules:
    host: tesopro-3860.front-qa-ms.clouditauchile.cl
    path: "/"   

resources:
  limits:
    cpu: 270m
    memory: 479Mi
  requests:
    memory: 220Mi
    cpu: 103m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

istio:
  enableSidecarInjection: true